[test]
preload = ["./setup.ts"]

[resolve]
extensions = [".ts", ".tsx", ".js", ".jsx"]

[resolve.alias]
"@" = "./src"
"@service" = "./src/shared/services"
"@agent" = "./src/agents"
"@shared" = "./src/shared"
"@types" = "./src/types" 